const SAVE_ACTION_TYPE = {
  SAVE_ALBUM_HOT: "SAVE_ALBUM_HOT",
  SAVE_NEWS: "SAVE_NEWS",
  SAVE_PLAYLIST: "SAVE_PLAYLIST",
  SAVE_SINGER: "SAVE_SINGER",
  SAVE_VPOP: "SAVE_VPOP",
  SAVE_SONG_RATING_TOP: "SAVE_SONG_RATING_TOP",
  SAVE_SONG_RATING: "SAVE_SONG_RATING",
  SAVE_VIDEO_HOT: "SAVE_VIDEO_HOT",
  SAVE_ZINGCHART_ALBUM: "SAVE_ZINGCHART_ALBUM",
  SAVE_ZINGCHART_MV: "SAVE_ZINGCHART_MV",
  SAVE_ZINGCHART_SONG: "SAVE_ZINGCHART_SONG",
};
export default SAVE_ACTION_TYPE;
